runtime: python
env: flex
entrypoint: gunicorn -b :$PORT service:Service

runtime_config:
  python_version: 3

# [START gae_flex_pubsub_env]
env_variables:
    STORE_URI_NAME: ""
    STORE_DATABASE_NAME: envvars
    STORE_TABLE_NAME: iottutorial
    

# [END gae_flex_pubsub_env]